package:
  name: orlssvm  
  version: "1.0"

source:  
  git_url:  https://github.com/QuantField/orlssvm.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports: 
    - orlssvm
    

about:
  home: https://github.com/QuantField/orlssvm
  license: BSD